### PR TITLE
Add HRI23 Video Submission

### PR DESCRIPTION
**Pull request by amalnanavati**
NOTE: This submission is technically both a YouTube video and a 2 page paper. I don't think we currently have the capability to add two links to the website. I've linked the video from the to the BibTex file, and added the the paper to the Google Drive https://drive.google.com/file/d/1ciXbUttJz3bR-FJq9dKXFtsFvjqxp70c/view?usp=sharing , but the paper isn't currently linked from the website.

LMK if you have suggestions on getting both links reflected.

- [X] Update `.bib` file
- [?] Upload publication PDF to [Google Drive](https://drive.google.com/drive/folders/1M9fOGIIQ3e1R62dtVit5rZ5iWZqxfWV9)

### CODE REVIEW

**Comment by amalnanavati** [comment]
I took a stab at it by adding a note with a link to the PDF. I'm not sure if it will work for two reasons:
1. Will our script actually pull `nanavati2023unintended` from the [Google Drive](https://drive.google.com/file/d/1ciXbUttJz3bR-FJq9dKXFtsFvjqxp70c/view?usp=sharing) into the website domain if that publication has a separate URL?
2. I'm not sure if our script can parse `href` in the notes tag.

(I'm guessing @egordon is the most familiar with how the script pulls files from the Google Drive)

**Comment by egordon** [comment]
@amalnanavati By default the script will pull the file with the same name as the bibtex entry into the website and create a link there over the title text.

Seeing here: https://github.com/personalrobotics/prl-website/blob/master/personalrobotics/main/publications.py

The only fields that the website currently looks at are "title", "author", "booktitle", "year", and optionally "note".

So I would remove the URL tag, and replace the note tag with the URL of the Youtube Video. The PDF will be linked automatically from the title.

**Review by egordon — CHANGES_REQUESTED** [review]
See previous comment

**Comment by egordon** [comment]
Update: apologies, it looks like it does indeed look at "url" for optional_publink. I think this will work.

**Review by egordon — APPROVED** [review]
Mad a change to prl-website to parse a single href tag in the note. See https://github.com/personalrobotics/prl-website/commit/1a6628879817bb97f6419caa634c4ab745496ad1

If check passes, this should be good to merge.

**Pull request merged**
